INSERT INTO `USUARIO` (ID, LOGIN, NOME, SENHA) VALUES (1, 'ADM', 'ADMINISTRADOR', 'ADM');
INSERT INTO `GESTOR` (ID, LOGIN, NOME, SENHA) VALUES (1, 'GM', 'GESTOR', 'GM');
INSERT INTO `SOLICITANTE` (ID, LOGIN, NOME, SENHA) VALUES (1, 'SC', 'SOLICITANTE', 'SC');