INSERT INTO `USUARIO` (ID, LOGIN, NOME, SENHA) VALUES (1, 'ADM', 'Paulo', 'ADM');
INSERT INTO `GESTOR` (ID, LOGIN, NOME, SENHA) VALUES (2, 'GM', 'Pedro', 'GM');
INSERT INTO `SOLICITANTE` (ID, LOGIN, NOME, SENHA, TIPO_USUARIO) VALUES (3, 'SC', 'João', 'SC', 1);